### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by rome-user** [hraban/app-plist-copy#2]
Hello,

I am interested in using this home-manager module with the following use case:

- Use Home Manager to manage "global packages"
- Install Mac OS apps, like Emacs, and have it automatically appear in ~/Applications, Spotlight, etc.

I have set up home-manager with this module. Are there any extra steps one has to do after e.g. updating Emacs? Or does this get handled automatically when running `nix flake update && home-manager switch` ?

**Comment by hraban** [comment]
Yes, that should be all that's necessary: just import it and it should work. Let me know if it doesn't because I only use home-manager through nix-darwin so I've never tested it stand-alone.

There Re the operaton not permitted: that's a dockutil problem, there's been an open PR on nixpkgs since Mar 3: https://github.com/NixOS/nixpkgs/pull/293032 but it's languishing. Please vote on it to bump it up the priority list. In the mean time you'll have to import that dockutil separately and overlay it in your own config. :/ 

Honestly at this point I'm tempted to just add an override in the flake.nix for this project, the PR has been open so long it's getting ridiculous.
